In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [48]:
df=pd.read_csv(r"D:\Downloads From Teams DEPI\Life Expectancy Data.csv")

In [49]:
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [52]:
pd.set_option("display.max_columns",None)

In [54]:
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [55]:
df.shape

(2938, 22)

In [56]:
df.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   object
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   object
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  Schooling                        2775 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.1+ KB

In [58]:
df[df.duplicated()]

Empty DataFrame
Columns: [Country, Year, Status, Life expectancy , Adult Mortality, infant deaths, Alcohol, percentage expenditure, Hepatitis B, Measles ,  BMI , under-five deaths , Polio, Total expenditure, Diphtheria ,  HIV/AIDS, GDP, Population,  thinness  1-19 years,  thinness 5-9 years, Income composition of resources, Schooling]
Index: []

In [59]:
df.describe()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2938.000000,2928.000000,2928.000000,2938.000000,2744.000000,2938.000000,2385.000000,2938.000000,2904.000000,2938.000000,2919.000000,2712.00000,2919.000000,2938.000000,2490.000000,2.286000e+03,2904.000000,2904.000000,2771.000000,2775.000000
mean,2007.518720,69.224932,164.796448,30.303948,4.602861,738.251295,80.940461,2419.592240,38.321247,42.035739,82.550188,5.93819,82.324084,1.742103,7483.158469,1.275338e+07,4.839704,4.870317,0.627551,11.992793
std,4.613841,9.523867,124.292079,117.926501,4.052413,1987.914858,25.070016,11467.272489,20.044034,160.445548,23.428046,2.49832,23.716912,5.077785,14270.169342,6.101210e+07,4.420195,4.508882,0.210904,3.358920
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.37000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2004.000000,63.100000,74.000000,0.000000,0.877500,4.685343,77.000000,0.000000,19.300000,0.000000,78.000000,4.26000,78.000000,0.100000,463.935626,1.957932e+05,1.600000,1.500000,0.493000,10.100000
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.75500,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000
75%,2012.000000,75.700000,228.000000,22.000000,7.702500,441.534144,97.000000,360.250000,56.200000,28.000000,97.000000,7.49250,97.000000,0.800000,5910.806335,7.420359e+06,7.200000,7.200000,0.779000,14.300000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.60000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

In [60]:
df.select_dtypes(include=['int','float']).corr()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
Year,1.000000,0.170033,-0.079052,-0.037415,-0.052990,0.031400,0.104333,-0.082493,0.108974,-0.042937,0.094158,0.090740,0.134337,-0.139741,0.101620,0.016969,-0.047876,-0.050929,0.243468,0.209400
Life expectancy,0.170033,1.000000,-0.696359,-0.196557,0.404877,0.381864,0.256762,-0.157586,0.567694,-0.222529,0.465556,0.218086,0.479495,-0.556556,0.461455,-0.021538,-0.477183,-0.471584,0.724776,0.751975
Adult Mortality,-0.079052,-0.696359,1.000000,0.078756,-0.195848,-0.242860,-0.162476,0.031176,-0.387017,0.094146,-0.274823,-0.115281,-0.275131,0.523821,-0.296049,-0.013647,0.302904,0.308457,-0.457626,-0.454612
infant deaths,-0.037415,-0.196557,0.078756,1.000000,-0.115638,-0.085612,-0.223566,0.501128,-0.227279,0.996629,-0.170689,-0.128616,-0.175171,0.025231,-0.108427,0.556801,0.465711,0.471350,-0.145139,-0.193720
Alcohol,-0.052990,0.404877,-0.195848,-0.115638,1.000000,0.341285,0.087549,-0.051827,0.330408,-0.112370,0.221734,0.296942,0.222020,-0.048845,0.354712,-0.035252,-0.428795,-0.417414,0.450040,0.547378
percentage expenditure,0.031400,0.381864,-0.242860,-0.085612,0.341285,1.000000,0.016274,-0.056596,0.228700,-0.087852,0.147259,0.174420,0.143624,-0.097857,0.899373,-0.025662,-0.251369,-0.252905,0.381952,0.389687
Hepatitis B,0.104333,0.256762,-0.162476,-0.223566,0.087549,0.016274,1.000000,-0.120529,0.150380,-0.233126,0.486171,0.058280,0.611495,-0.112675,0.083903,-0.123321,-0.120429,-0.124960,0.199549,0.231117
Measles,-0.082493,-0.157586,0.031176,0.501128,-0.051827,-0.056596,-0.120529,1.000000,-0.175977,0.507809,-0.136166,-0.106241,-0.141882,0.030899,-0.076466,0.265966,0.224808,0.221072,-0.129568,-0.137225
BMI,0.108974,0.567694,-0.387017,-0.227279,0.330408,0.228700,0.150380,-0.175977,1.000000,-0.237669,0.284569,0.242503,0.283147,-0.243717,0.301557,-0.072301,-0.532025,-0.538911,0.508774,0.546961
under-five deaths,-0.042937,-0.222529,0.094146,0.996629,-0.112370,-0.087852,-0.233126,0.507809,-0.237669,1.000000,-0.188720,-0.130148,-0.195668,0.038062,-0.112081,0.544423,0.467789,0.472263,-0.163305,-0.209373
Polio,0.094158,0.465556,-0.274823,-0.170689,0.221734,0.147259,0.486171,-0.136166,0.284569,-0.188720,1.000000,0.137330,0.673553,-0.159560,0.211976,-0.038540,-0.221823,-0.222592,0.381078,0.417866
Total expenditure,0.090740,0.218086,-0.115281,-0.128616,0.296942,0.174420,0.058280,-0.106241,0.242503,-0.130148,0.137330,1.000000,0.152754,-0.001389,0.138364,-0.079662,-0.277101,-0.283774,0.166682,0.246384
Diphtheria,0.134337,0.479495,-0.275131,-0.175171,0.222020,0.143624,0.611495,-0.141882,0.283147,-0.195668,0.673553,0.152754,1.000000,-0.164860,0.200666,-0.028444,-0.229518,-0.222743,0.401456,0.425332
HIV/AIDS,-0.139741,-0.556556,0.523821,0.025231,-0.048845,-0.097857,-0.112675,0.030899,-0.243717,0.038062,-0.159560,-0.001389,-0.164860,1.000000,-0.136491,-0.027854,0.204064,0.207283,-0.249519,-0.220429
GDP,0.101620,0.461455,-0.296049,-0.108427,0.354712,0.899373,0.083903,-0.076466,0.301557,-0.112081,0.211976,0.138364,0.200666,-0.136491,1.000000,-0.028270,-0.285697,-0.290539,0.460341,0.448273
Population,0.016969,-0.021538,-0.013647,0.556801,-0.035252,-0.025662,-0.123321,0.265966,-0.072301,0.544423,-0.038540,-0.079662,-0.028444,-0.027854,-0.028270,1.000000,0.253944,0.251403,-0.008735,-0.031668
thinness 1-19 years,-0.047876,-0.477183,0.302904,0.465711,-0.428795,-0.251369,-0.120429,0.224808,-0.532025,0.467789,-0.221823,-0.277101,-0.229518,0.204064,-0.285697,0.253944,1.000000,0.939102,-0.422429,-0.471652
thinness 5-9 years,-0.050929,-0.471584,0.308457,0.471350,-0.417414,-0.252905,-0.124960,0.221072,-0.538911,0.472263,-0.222592,-0.283774,-0.222743,0.207283,-0.290539,0.251403,0.939102,1.000000,-0.411053,-0.460632
Income composition of resources,0.243468,0.724776,-0.457626,-0.145139,0.450040,0.381952,0.199549,-0.129568,0.508774,-0.163305,0.381078,0.166682,0.401456,-0.249519,0.460341,-0.008735,-0.422429,-0.411053,1.000000,0.800092
Schooling,0.209400,0.751975,-0.454612,-0.193720,0.547378,0.389687,0.231117,-0.137225,0.546961,-0.209373,0.417866,0.246384,0.425332,-0.220429,0.448273,-0.031668,-0.471652,-0.460632,0.800092,1.000000

In [67]:
for i in df.columns:
    if df[i].dtype == 'object':
        df[i] = df[i].str.strip()

In [64]:
df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,27.1,42,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,26.7,41,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,26.3,40,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,25.9,39,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,25.5,39,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [41]:
df.columns

Index(['Country', 'Year', 'Status', 'Life expectancy', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles', 'BMI', 'under-five deaths', 'Polio', 'Total expenditure',
       'Diphtheria', 'HIV/AIDS', 'GDP', 'Population', 'thinness  1-19 years',
       'thinness 5-9 years', 'Income composition of resources', 'Schooling'],
      dtype='object')

In [45]:
df.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
BMI                                 34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
HIV/AIDS                             0
GDP                                448
Population                         652
thinness  1-19 years                34
thinness 5-9 years                  34
Income composition of resources    167
Schooling                          163
dtype: int64

In [99]:
c = df[['Adult Mortality', 'BMI', 'HIV/AIDS', 'Income composition of resources', 'Schooling','thinness  1-19 years', 'thinness 5-9 years','Polio','percentage expenditure','Alcohol']]
c

,Adult Mortality,BMI,HIV/AIDS,Income composition of resources,Schooling,thinness 1-19 years,thinness 5-9 years,Polio,percentage expenditure,Alcohol
0,263.0,19.1,0.1,0.479,10.1,17.2,17.3,6.0,71.279624,0.01
1,271.0,18.6,0.1,0.476,10.0,17.5,17.5,58.0,73.523582,0.01
2,268.0,18.1,0.1,0.470,9.9,17.7,17.7,62.0,73.219243,0.01
3,272.0,17.6,0.1,0.463,9.8,17.9,18.0,67.0,78.184215,0.01
4,275.0,17.2,0.1,0.454,9.5,18.2,18.2,68.0,7.097109,0.01
...,...,...,...,...,...,...,...,...,...,...
2933,723.0,27.1,33.6,0.407,9.2,9.4,9.4,67.0,0.000000,4.36
2934,715.0,26.7,36.7,0.418,9.5,9.8,9.9,7.0,0.000000,4.06
2935,73.0,26.3,39.8,0.427,10.0,1.2,1.3,73.0,0.000000,4.43
2936,686.0,25.9,42.1,0.427,9.8,1.6,1.7,76.0,0.000000,1.72
2937,665.0,25.5,43.5,0.434,9.8,11.0,11.2,78.0,0.000000,1.68

In [100]:
c.isnull().sum()

Adult Mortality                     10
BMI                                 34
HIV/AIDS                             0
Income composition of resources    167
Schooling                          163
thinness  1-19 years                34
thinness 5-9 years                  34
Polio                               19
percentage expenditure               0
Alcohol                            194
dtype: int64

In [101]:
for i in c.columns:  
    if c[i].isnull().any():  
        v = c[i].mode()[0]  
        c[i].fillna(v, inplace=True)

C:\Users\test\AppData\Local\Temp\ipykernel_6756\2835991227.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  c[i].fillna(v, inplace=True)
C:\Users\test\AppData\Local\Temp\ipykernel_6756\2835991227.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c[i].fillna(v, inplace=True)

In [103]:
c.isnull().sum()

Adult Mortality                    0
BMI                                0
HIV/AIDS                           0
Income composition of resources    0
Schooling                          0
thinness  1-19 years               0
thinness 5-9 years                 0
Polio                              0
percentage expenditure             0
Alcohol                            0
dtype: int64

In [104]:
from sklearn .metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

In [105]:
val=df['Life expectancy'].mode()[0]
df['Life expectancy'].fillna(val,inplace=True)

In [107]:
x

array([[2.63000000e+02, 1.91000000e+01, 1.00000000e-01, ...,
        6.00000000e+00, 7.12796236e+01, 1.00000000e-02],
       [2.71000000e+02, 1.86000000e+01, 1.00000000e-01, ...,
        5.80000000e+01, 7.35235817e+01, 1.00000000e-02],
       [2.68000000e+02, 1.81000000e+01, 1.00000000e-01, ...,
        6.20000000e+01, 7.32192427e+01, 1.00000000e-02],
       ...,
       [7.30000000e+01, 2.63000000e+01, 3.98000000e+01, ...,
        7.30000000e+01, 0.00000000e+00, 4.43000000e+00],
       [6.86000000e+02, 2.59000000e+01, 4.21000000e+01, ...,
        7.60000000e+01, 0.00000000e+00, 1.72000000e+00],
       [6.65000000e+02, 2.55000000e+01, 4.35000000e+01, ...,
        7.80000000e+01, 0.00000000e+00, 1.68000000e+00]], shape=(2938, 10))

In [113]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=0,test_size=0.2)
scale=StandardScaler()
xtrainS=scale.fit_transform(xtrain)
xtestS=scale.transform(xtest)

In [109]:
model=LinearRegression()

In [110]:
model.fit(xtrainS,ytrain)
ypred=model.predict(xtestS)
acc=r2_score(ytest,ypred)
acc

0.8052551058826305

In [111]:
c.isnull().sum()

Adult Mortality                    0
BMI                                0
HIV/AIDS                           0
Income composition of resources    0
Schooling                          0
thinness  1-19 years               0
thinness 5-9 years                 0
Polio                              0
percentage expenditure             0
Alcohol                            0
dtype: int64

In [126]:
from sklearn.ensemble import RandomForestRegressor
import pickle

model=RandomForestRegressor()
model.fit(xtrainS,ytrain)
ypred=model.predict(xtestS)
accuracy=r2_score(ytest,ypred)

accuracy=round(accuracy,2)*100
print("Test R² Score",accuracy,"%")
pickle.dump(model,open(r"C:\Users\test\DEPI Project\Project ws.pkl", "wb"))

Test R² Score 96.0 %

In [118]:
import xgboost as xgb
model=xgb.XGBRegressor(learning_rate=0.5)
model.fit(xtrainS,ytrain)
ypred=model.predict(xtestS)
accuracy=r2_score(ytest,ypred)

accuracy=round(accuracy,2)*100
print("Test R² Score",accuracy,"%")

Test R² Score 95.0 %